"""WordPress REST API client using Application Password authentication."""

import base64
import mimetypes
import time
from pathlib import Path
from typing import Any, Optional

import httpx


class WordPressClient:
    """Client for the WordPress REST API (wp-json/wp/v2) with retry logic."""

    def __init__(
        self,
        base_url: str,
        username: str,
        app_password: str,
        max_retries: int = 3,
        timeout: float = 30.0,
    ) -> None:
        """
        Initialise the WordPress client.

        Args:
            base_url: WordPress site root URL (e.g. https://example.com).
            username: WordPress login username.
            app_password: WordPress Application Password (spaces ignored).
            max_retries: Retry count for transient network/server errors.
            timeout: Per-request timeout in seconds.
        """
        self.base_url = base_url.rstrip("/")
        self.api_base = f"{self.base_url}/wp-json/wp/v2"
        self.max_retries = max(1, max_retries)
        self.timeout = timeout

        creds = f"{username}:{app_password.replace(' ', '')}"
        encoded = base64.b64encode(creds.encode()).decode()
        self._auth_header = f"Basic {encoded}"

    # ------------------------------------------------------------------ #
    #  Internal HTTP helper                                                #
    # ------------------------------------------------------------------ #

    def _request(self, method: str, endpoint: str, **kwargs: Any) -> dict:
        """
        Make an authenticated request with exponential-backoff retries.

        Args:
            method: HTTP verb (GET, POST, PUT, DELETE).
            endpoint: Path relative to wp-json/wp/v2 (leading slash optional).
            **kwargs: Passed verbatim to httpx.Client.request().

        Returns:
            Parsed JSON response dict.

        Raises:
            RuntimeError: On auth failure, 404, or exhausted retries.
        """
        url = f"{self.api_base}/{endpoint.lstrip('/')}"
        headers: dict = kwargs.pop("headers", {})
        headers["Authorization"] = self._auth_header
        headers.setdefault("Accept", "application/json")

        last_error = "Unknown error"
        attempts = self.max_retries if method.upper() == "GET" else 1
        for attempt in range(attempts):
            try:
                with httpx.Client(timeout=self.timeout) as client:
                    response = client.request(method, url, headers=headers, **kwargs)

                if response.status_code in (200, 201):
                    return response.json()

                body_preview = response.text[:500]
                if response.status_code in (401, 403):
                    raise RuntimeError(
                        f"WordPress authentication failed ({response.status_code}): {body_preview}"
                    )
                if response.status_code == 404:
                    raise RuntimeError(f"WordPress endpoint not found: {url}")

                last_error = f"HTTP {response.status_code}"
                if response.status_code < 500 and response.status_code not in (408, 429):
                    raise RuntimeError(last_error)

            except (httpx.ConnectError, httpx.TimeoutException) as exc:
                last_error = str(exc)

            if attempt < attempts - 1:
                time.sleep(2**attempt)

        raise RuntimeError(f"WordPress API request failed after {attempts} attempts: {last_error}")

    # ------------------------------------------------------------------ #
    #  Public API                                                          #
    # ------------------------------------------------------------------ #

    def create_post(
        self,
        title: str,
        content: str,
        status: str = "draft",
        slug: Optional[str] = None,
        meta_description: Optional[str] = None,
        categories: Optional[list[int]] = None,
        tags: Optional[list[int]] = None,
    ) -> dict:
        """
        Create a new WordPress post.

        Args:
            title: Post title.
            content: HTML post body.
            status: "draft", "publish", or "private".
            slug: Custom URL slug; auto-generated by WordPress if omitted.
            meta_description: Summary stored in the native WordPress excerpt field.
            categories: Category IDs to assign.
            tags: Tag IDs to assign.

        Returns:
            Dict with post_id, title, link, status, slug.
        """
        if status not in {"draft", "publish", "private"}:
            raise ValueError("Unsupported WordPress post status")
        if not title.strip() or not content.strip():
            raise ValueError("Post title and content are required")
        payload: dict[str, Any] = {"title": title, "content": content, "status": status}
        if slug:
            payload["slug"] = slug
        if categories:
            payload["categories"] = categories
        if tags:
            payload["tags"] = tags
        if meta_description:
            payload["excerpt"] = meta_description

        result = self._request("POST", "posts", json=payload)
        return {
            "post_id": result.get("id"),
            "title": (result.get("title") or {}).get("rendered"),
            "link": result.get("link"),
            "status": result.get("status"),
            "slug": result.get("slug"),
        }

    def update_post(self, post_id: int, **fields: Any) -> dict:
        """
        Update an existing post by ID.

        Args:
            post_id: WordPress post ID.
            **fields: Any writable post fields (title, content, status, etc.).

        Returns:
            Dict with post_id, title, link, status.
        """
        result = self._request("POST", f"posts/{post_id}", json=fields)
        return {
            "post_id": result.get("id"),
            "title": (result.get("title") or {}).get("rendered"),
            "link": result.get("link"),
            "status": result.get("status"),
        }

    def upload_media(
        self,
        file_path: str,
        filename: Optional[str] = None,
        alt_text: Optional[str] = None,
    ) -> dict:
        """
        Upload a file to the WordPress Media Library.

        Args:
            file_path: Absolute or relative local path to the file.
            filename: Override the upload filename; defaults to the basename.
            alt_text: Accessibility alt text for images.

        Returns:
            Dict with media_id and source_url.
        """
        path = Path(file_path)
        name = filename or path.name
        mime_type, _ = mimetypes.guess_type(name)
        mime_type = mime_type or "application/octet-stream"

        file_bytes = path.read_bytes()
        headers = {
            "Content-Disposition": f'attachment; filename="{name}"',
            "Content-Type": mime_type,
        }
        result = self._request("POST", "media", headers=headers, content=file_bytes)

        media_id = result.get("id")
        if alt_text and media_id:
            self._request("POST", f"media/{media_id}", json={"alt_text": alt_text})

        return {
            "media_id": media_id,
            "source_url": result.get("source_url"),
            "filename": result.get("slug"),
        }

    def set_featured_image(self, post_id: int, media_id: int) -> dict:
        """
        Set the featured image (thumbnail) on a post.

        Args:
            post_id: WordPress post ID.
            media_id: Media library item ID to use as featured image.

        Returns:
            Dict with post_id and featured_media.
        """
        result = self._request("POST", f"posts/{post_id}", json={"featured_media": media_id})
        return {
            "post_id": result.get("id"),
            "featured_media": result.get("featured_media"),
        }

    def get_post(self, post_id: int) -> dict:
        """
        Retrieve a post by ID.

        Args:
            post_id: WordPress post ID.

        Returns:
            Raw WordPress post object dict.
        """
        return self._request("GET", f"posts/{post_id}")

    def test_connection(self) -> bool:
        """
        Verify that credentials and connectivity are valid.

        Returns:
            True on success.

        Raises:
            RuntimeError: If authentication or network fails.
        """
        self._request("GET", "users/me")
        return True


# ------------------------------------------------------------------ #
#  Convenience function                                               #
# ------------------------------------------------------------------ #


def publish_to_wordpress(
    wp_url: str,
    wp_user: str,
    wp_password: str,
    title: str,
    content: str,
    meta_description: str = "",
    status: str = "draft",
) -> dict:
    """
    Convenience wrapper that creates a WordPress post in one call.

    Args:
        wp_url: WordPress site URL.
        wp_user: WordPress username.
        wp_password: WordPress Application Password.
        title: Post title.
        content: HTML post body.
        meta_description: SEO meta description.
        status: "draft" or "publish".

    Returns:
        Dict with post_id, title, link, status, slug.
    """
    client = WordPressClient(wp_url, wp_user, wp_password)
    return client.create_post(
        title=title,
        content=content,
        meta_description=meta_description,
        status=status,
    )
